### ISSUE TITLE
Alternative displays

### ISSUE THREAD

**Issue by tkrebby** [azmatt/chasing_your_tail#11]
Currently using a 3.5" LCD touchscreen for my Pi (http://www.lcdwiki.com/3.5inch_RPi_Display).  For whatever reason, the GUI script errors out with this display:

```
Traceback (most recent call last):
  File "/home/kraken/chasing_your_tail/cyt_gui.py", line 27, in <module>
    root = tk.Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

Any advice?

**Comment by transistor1** [comment]
Not familiar with this project, and you didn't provide much detail, but typically that error means that your terminal can't find an Xserver (a graphical interface for GNU/Linux). This is usually because your terminal is misconfigured, you're not using a graphical environment, or you're trying to run a graphical application over SSH. 

The python module `tkinter`, that's referenced in your error, is used for building window interfaces for desktop use, and thus can't be used in a non-graphical environment. 

Now, presuming your pi is running a desktop environment (that is, a graphical window manager), you can try something like:
```
export DISPLAY=unix:0.0
```
... and then try running the Python script.  This should also work even if you are SSH'ing into the pi but it does have a graphical desktop running on the LCD. If 0.0 doesn't work, you can also try 1.0, 2.0, etc..., in case the Xserver is running on a different screen number. 

If it works, you may then need to figure out exactly why your terminal isn't setting the `DISPLAY` variable itself, to come up with a more permanent solution. 

Good luck!

**Comment by gcv-javier** [comment]
Hi @tkrebby, I've recently been abled to configure everything on a Raspberry Pi 4, using the **same screen** you are using. The app is working nicely. Matt did a great job.
I'm using another antenna, although very similar, with the same chipset, the AWUS036AC antenna.

When following the instructions, I noticed a missing thing on the **prereqs.pdf** about the _cyt_gui.sh_ that is mentioned.
This file is not in the repository. But I guessed how it would look like. 
I created one **cyt_gui.sh** file whose content is: **_python3 cyt_gui.py func_run_cyt_**
This calls a specific function in the python file.

With the screen pen, you can double click on the new cyt_gui.sh file, execute it and the GUI is loaded.
I used the same folders structure that appears on the prereqs.pdf (to avoid misconfigurations):
 
/home/pi/Desktop/ (contains the content of the chasing_your_tail/ folder if you'd do gitclone, I had to move the content outside and delete the chasing_your_tail/ folder)
_/home/pi/Desktop/cyt_gui.sh
/home/pi/Desktop/cyt_gui.py
/home/pi/Desktop/prereqs.pdf_
.....
_/home/pi/Desktop/cyt_ (the folder with the main code and scripts)

That way the **cyt_gui.sh** calls the **cyt_gui.py**.

Although I suppose Matt idea was using **xdg** to autostart the GUI when the OS starts, but this is not working in my case and I have to double click on the cyt_gui.sh to run the GUI. 

I hope this helps.

P.S.: Did you install the screen drivers? First thing to do. From SSH. Mine were found in https://github.com/goodtft/LCD-show.
git clone https://github.com/goodtft/LCD-show.git
chmod -R 755 LCD-show
cd LCD-show
sudo ./LCD35-show
and reboot the raspberry.

**Comment by tkrebby** [comment]
Thanks for the help and support, got it working based on the feedback.
